services:
  - type: web
    name: igjf-backend
    env: node
    region: oregon
    plan: free
    branch: deployment-cleanup
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static
    name: igjf-frontend
    region: oregon
    plan: free
    branch: deployment-cleanup
    buildCommand: cd mobile-app && npm install && npm run build:web && rm -rf dist-merged && mkdir -p dist-merged && cp -r dist/server/* dist-merged/ && cp -r dist/client/* dist-merged/
    staticPublishPath: mobile-app/dist-merged
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff