services:
  - type: web
    name: igjf-backend
    env: node
    region: oregon
    plan: free
    branch: deployment-cleanup
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: igjf-frontend
    env: static
    region: oregon
    plan: free
    branch: deployment-cleanup
    buildCommand: cd mobile-app && npm install && npm run build:web
    staticPublishPath: mobile-app/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff