services:
  - type: web
    name: igjf-backend
    env: node
    region: singapore
    plan: free
    branch: deployment-cleanup
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: static
    name: igjf-frontend
    region: global
    plan: free
    branch: deployment-cleanup
    rootDir: mobile-app
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: dist-merged
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://igjf-app.onrender.com/api
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff